hostNetwork: false

ingressClass:
  enabled: true
  isDefaultClass: true
  name: traefik

providers:
  kubernetesIngress:
    publishedService:
      enabled: true

service:
  enabled: true
  type: LoadBalancer
