version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "ci"

  - package-ecosystem: "terraform"
    directory: "/01-provision"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "infra"
